# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 2 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  List:
    name: List open issues labeled "out-of-office"
    runs-on: ubuntu-latest
    steps:
      - name: List out-of-office issues
        uses: lee-dohm/select-matching-issues@v1
        with:
          format: list
          query: 'label:"purchase request"'
          token: ${{ github.token }}
